config/routes.rb
Rails.application.routes.draw do
  resources :recipes
  resources :tag_recipes
  resources :shops
  resources :items
  resources :tags
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "static#index"
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
end

app/models/recipe.rb
class Recipe < ApplicationRecord
end

app/models/shop.rb
class Shop < ApplicationRecord
end

app/models/tag.rb
class Tag < ApplicationRecord
end

app/models/tag_recipe.rb
class TagRecipe < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
  end

end

app/controllers/items_controller.rb
class ItemsController < InheritedResources::Base

  private

    def item_params
      params.require(:item).permit(:tag_id, :shop_id, :name, :stock, :price)
    end
end

app/controllers/recipes_controller.rb
class RecipesController < InheritedResources::Base

  def show
    id = params[:id]
    if params[:id].nil? then id=1 end
    @recipe = Recipe.find(id)
    @tag_recipes = TagRecipe.where(recipe_id: id)
    @tags = Tag.where(id: @tag_recipes.pluck("tag_id"))
  end

  private

    def recipe_params
      params.require(:recipe).permit(:name, :description)
    end
end

app/controllers/shops_controller.rb
class ShopsController < InheritedResources::Base

  private

    def shop_params
      params.require(:shop).permit(:name, :adress, :business_hours, :GPS)
    end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
    def index
    end
end

app/controllers/tag_recipes_controller.rb
class TagRecipesController < InheritedResources::Base

  private

    def tag_recipe_params
      params.require(:tag_recipe).permit(:recipe_id, :tag_id, :require)
    end
end

app/controllers/tags_controller.rb
class TagsController < InheritedResources::Base

  def index
    if  ! params[:tag_action].nil? then
      recipe_id = params[:recipe_id]
      @tag_recipes = TagRecipe.where(recipe_id: recipe_id).order("tag_id")
      @tags = Tag.where(id: @tag_recipes.pluck("tag_id"))
    else
      if ! params[:query].nil? then
        query = params[:query].split(" ")
        @tags = Tag.where.like(name: query)
      else
        @tags = Tag.all
      end
    end

    @search_query = params[:query]

    tag_ids = @tags.pluck("id")
    @tag_ids = tag_ids
    item = Item.where(tag_id: tag_ids)
    shop_ids = item.pluck("shop_id")
    @shops = Shop.where(id: shop_ids)
  end

  private

    def tag_params
      params.require(:tag).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/shops_helper.rb
module ShopsHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/helpers/tag_recipes_helper.rb
module TagRecipesHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/items/_form.html.erb
<%= form_with(model: item, local: true) do |form| %>
  <% if item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :tag_id %>
    <%= form.number_field :tag_id, id: :item_tag_id %>
  </div>

  <div class="field">
    <%= form.label :shop_id %>
    <%= form.number_field :shop_id, id: :item_shop_id %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :item_name %>
  </div>

  <div class="field">
    <%= form.label :stock %>
    <%= form.number_field :stock, id: :item_stock %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.number_field :price, id: :item_price %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/items/edit.html.erb
<h1>Editing Item</h1>

<%= render 'form', item: @item %>

<%= link_to 'Show', @item %> |
<%= link_to 'Back', items_path %>

app/views/items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Items</h1>

<table>
  <thead>
    <tr>
      <th>Tag</th>
      <th>Shop</th>
      <th>Name</th>
      <th>Stock</th>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @items.each do |item| %>
      <tr>
        <td><%= item.tag_id %></td>
        <td><%= item.shop_id %></td>
        <td><%= item.name %></td>
        <td><%= item.stock %></td>
        <td><%= item.price %></td>
        <td><%= link_to 'Show', item %></td>
        <td><%= link_to 'Edit', edit_item_path(item) %></td>
        <td><%= link_to 'Destroy', item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Item', new_item_path %>

app/views/items/new.html.erb
<h1>New Item</h1>

<%= render 'form', item: @item %>

<%= link_to 'Back', items_path %>

app/views/items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Tag:</strong>
  <%= @item.tag_id %>
</p>

<p>
  <strong>Shop:</strong>
  <%= @item.shop_id %>
</p>

<p>
  <strong>Name:</strong>
  <%= @item.name %>
</p>

<p>
  <strong>Stock:</strong>
  <%= @item.stock %>
</p>

<p>
  <strong>Price:</strong>
  <%= @item.price %>
</p>

<%= link_to 'Edit', edit_item_path(@item) %> |
<%= link_to 'Back', items_path %>

app/views/recipes/_form.html.erb
<%= form_with(model: recipe, local: true) do |form| %>
  <% if recipe.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(recipe.errors.count, "error") %> prohibited this recipe from being saved:</h2>

      <ul>
      <% recipe.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :recipe_name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description, id: :recipe_description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/recipes/edit.html.erb
<h1>Editing Recipe</h1>

<%= render 'form', recipe: @recipe %>

<%= link_to 'Show', @recipe %> |
<%= link_to 'Back', recipes_path %>

app/views/recipes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Recipes</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @recipes.each do |recipe| %>
      <tr>
        <td><%= recipe.name %></td>
        <td><%= recipe.description %></td>
        <td><%= link_to 'Show', recipe %></td>
        <td><%= link_to 'Edit', edit_recipe_path(recipe) %></td>
        <td><%= link_to 'Destroy', recipe, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Recipe', new_recipe_path %>

app/views/recipes/new.html.erb
<h1>New Recipe</h1>

<%= render 'form', recipe: @recipe %>

<%= link_to 'Back', recipes_path %>

app/views/recipes/show.html.erb
<div class="block_main">
  <header class="block_header_no_search">
    <div class="header_log_image_box_no_search">
      <a href="/"><%= image_tag 'logo.png', :height => "80%" %></a>
    </div>
  </header>
  <% flag = 2 %>
  <div>
    <table>
      <tr><td><%= @recipe.name %></td></tr>
      <tr><td><%= @recipe.description %></td></tr>
      <tr><td>1人分</td></tr>
      <% @tags.each do |tag| %>
        <% @tag_recipes.each do |tag_recipe| %>
          <% if tag_recipe.tag_id == tag.id then%>
            <% if flag%2 == 1 then%>
              <% flag+=1 %>
              <tr class="tr_glee"><td><%= tag.name %> : <%= tag_recipe.require%></td></tr>
            <% else %>
              <tr class="tr_white"><td><%= tag.name %> : <%= tag_recipe.require%></td></tr>
              <% flag+=1 %>
            <% end %>
            <% break %>
          <% end %>
        <% end %>
      <% end %>
    </table>
  </div>
  <div>
    <form action="/tags" method="get">
      <input type="hidden" name="tag_action" value="tag_query">
      <input type="hidden" name="recipe_id" value="<%= @recipe.id %>">
      <button type="submit" name="action" value="tag_search">店舗の在庫を確認する</button>
    </form>
  </div>
  <div>
    <%= image_tag 'carry_recipe', :width => "100%" %>
  </div>
</div>

app/views/shops/_form.html.erb
<%= form_with(model: shop, local: true) do |form| %>
  <% if shop.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(shop.errors.count, "error") %> prohibited this shop from being saved:</h2>

      <ul>
      <% shop.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :shop_name %>
  </div>

  <div class="field">
    <%= form.label :adress %>
    <%= form.text_field :adress, id: :shop_adress %>
  </div>

  <div class="field">
    <%= form.label :business_hours %>
    <%= form.text_field :business_hours, id: :shop_business_hours %>
  </div>

  <div class="field">
    <%= form.label :GPS %>
    <%= form.text_field :GPS, id: :shop_GPS %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/shops/edit.html.erb
<h1>Editing Shop</h1>

<%= render 'form', shop: @shop %>

<%= link_to 'Show', @shop %> |
<%= link_to 'Back', shops_path %>

app/views/shops/index.html.erb
<div class="block_main">
  <header class="block_header">
      <div class="header_search">
          <form action="/tags" method="get">
              <button type="submit" value="action" class="tmp_serach_button">a</button>
              <input name="query" type="text" placeholder="探したい食材で検索" class="form_input_search">
          </form>
      </div>
  </header>
  <div id="content_field" class="block_main_list">
      <% @shops.each do |shop| %>
      <div class="block_main_list_node">
          <table class="block_table">
              <tr>
                <td rowspan="3"><%= image_tag 'img_sample.jpg' %></td>
                <td class="block_list_shop_name"><%= shop.name %></td>
              </tr>
              <tr><td class="block_list_shop_info"><%= shop.adress %></td></tr>
              <tr><td class="block_list_shop_info"><%= shop.business_hours %></td></tr>
          </table>
      </div>
      <% end %>
  </div>
</div>

app/views/shops/new.html.erb
<h1>New Shop</h1>

<%= render 'form', shop: @shop %>

<%= link_to 'Back', shops_path %>

app/views/shops/show.html.erb
<div class="block_main">
<a href='/'><%= image_tag 'shop_show', :width => "100%" %></a>
</div>

app/views/tag_recipes/_form.html.erb
<%= form_with(model: tag_recipe, local: true) do |form| %>
  <% if tag_recipe.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tag_recipe.errors.count, "error") %> prohibited this tag_recipe from being saved:</h2>

      <ul>
      <% tag_recipe.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :recipe_id %>
    <%= form.number_field :recipe_id, id: :tag_recipe_recipe_id %>
  </div>

  <div class="field">
    <%= form.label :tag_id %>
    <%= form.number_field :tag_id, id: :tag_recipe_tag_id %>
  </div>

  <div class="field">
    <%= form.label :require %>
    <%= form.number_field :require, id: :tag_recipe_require %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/tag_recipes/edit.html.erb
<h1>Editing Tag Recipe</h1>

<%= render 'form', tag_recipe: @tag_recipe %>

<%= link_to 'Show', @tag_recipe %> |
<%= link_to 'Back', tag_recipes_path %>

app/views/tag_recipes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tag Recipes</h1>

<table>
  <thead>
    <tr>
      <th>Recipe</th>
      <th>Tag</th>
      <th>Require</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tag_recipes.each do |tag_recipe| %>
      <tr>
        <td><%= tag_recipe.recipe_id %></td>
        <td><%= tag_recipe.tag_id %></td>
        <td><%= tag_recipe.require %></td>
        <td><%= link_to 'Show', tag_recipe %></td>
        <td><%= link_to 'Edit', edit_tag_recipe_path(tag_recipe) %></td>
        <td><%= link_to 'Destroy', tag_recipe, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tag Recipe', new_tag_recipe_path %>

app/views/tag_recipes/new.html.erb
<h1>New Tag Recipe</h1>

<%= render 'form', tag_recipe: @tag_recipe %>

<%= link_to 'Back', tag_recipes_path %>

app/views/tag_recipes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Recipe:</strong>
  <%= @tag_recipe.recipe_id %>
</p>

<p>
  <strong>Tag:</strong>
  <%= @tag_recipe.tag_id %>
</p>

<p>
  <strong>Require:</strong>
  <%= @tag_recipe.require %>
</p>

<%= link_to 'Edit', edit_tag_recipe_path(@tag_recipe) %> |
<%= link_to 'Back', tag_recipes_path %>

app/views/tags/_form.html.erb
<%= form_with(model: tag, local: true) do |form| %>
  <% if tag.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tag.errors.count, "error") %> prohibited this tag from being saved:</h2>

      <ul>
      <% tag.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :tag_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/tags/edit.html.erb
<h1>Editing Tag</h1>

<%= render 'form', tag: @tag %>

<%= link_to 'Show', @tag %> |
<%= link_to 'Back', tags_path %>

app/views/tags/index.html.erb
<script>
  var tag_array = [];
  var shop_array = [];
  <% @tags.each do |tag|%>
      tag_array.push(<%= tag.id %>);
  <%end%>
  <% @shops.each do |shop|%>
      shop_array.push(<%= shop.id %>);
  <%end%>
  console.log(tag_array);
</script>
<%
  def stock_convert(num)
    if (num == 0) then
      return "×"
    elsif num > 3 then
      return "○"
    else
      return num
    end
  end
%>
<div class="block_main"> 
  <header class="block_header">
      <div class="header_log_image_box">
        <a href="/"><%= image_tag 'logo.png', :height => "80%" %></a>
      </div>
      <div class="header_search">
          <form action="/tags" method="get">
              <button type="submit" value="action" class="tmp_serach_button"><%= image_tag 'search.png', :size => "16x16"%></button>
              <input type="text" name="query" placeholder="探したい食材で検索" class="form_input_search" value="<%=@search_query %>">
          </form>
      </div>
  </header>
  <% tag_size = @tags.length %>
  <table name="search" class="searchTable">
    <thead>
      <tr>
        <% if ! @tag_recipes.nil? then%>
          <th class="search_box_C">レシピに必要な数</th>
          <% @tag_recipes.each do |tag_recipe| %>
            <th class="search_box_B"><%= tag_recipe.require %></th>
          <% end %>
        <% end %>
      </tr>
      <tr>
        <th class="search_box_A">多い順</th>
        <% @tags.each do |tag|%>
          <th class="search_box_A"><%= tag.name %></th>
        <%end%>
      </tr>
    </thead>
    <tbody>
  <% @shops.each do |shop| %>
      <tr>
        <td class="search_box_A"> <a href="/shops/1"><font class="link_font_table"><%= shop.name %></font></a></td>
    <% @tags.each do |tag| %>
        <%
          stock = rand(1..5)
        %>
        <td class="search_box_B" id="<%= shop.id %>_<%= tag.id %>" data-stock="<%= stock %>" ><%= stock_convert(stock)%></td>
    <% end %>
      </tr>
  <% end %>
    </tbody>
  </table>
  <h1><%= @action %></h1>
</div>
<script>
  function update_stock() {
    var tag_id = tag_array[Math.floor(Math.random() * tag_array.length)];
    var shop_id = shop_array[Math.floor(Math.random() * shop_array.length)];
    var id = `${shop_id}_${tag_id}`;
    console.log(id);
    var td = document.getElementById(id);
    stock = td.getAttribute('data-stock');
    td.setAttribute('data-stock', stock - 1)
    td.innerHTML = stock_convert(stock - 1);
  }
  function stock_convert (num) {
    if (num <= 0) {
      return "×";
    } else if (num > 3) {
      return "○";
    } else {
      return num;
    }
  }
  setInterval("update_stock()", 1000);
  setInterval("update_stock()", 500);
</script>

app/views/tags/new.html.erb
<h1>New Tag</h1>

<%= render 'form', tag: @tag %>

<%= link_to 'Back', tags_path %>

app/views/tags/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @tag.name %>
</p>

<%= link_to 'Edit', edit_tag_path(@tag) %> |
<%= link_to 'Back', tags_path %>